python src/baseline/majority_vote.py

python src/error_detection_analysis/calculate_performance.py
python src/error_detection_analysis/generate_performance_tables.py
python src/error_detection_analysis/generate_improvement_tables.py
python src/error_detection_analysis/generate_majority_vote_tables.py

python src/error_detection_analysis/bias_analysis.py
python src/error_detection_analysis/compare_to_other_tasks.py
python src/error_detection_analysis/analyze_self_consistency.py
